#!/bin/bash
#===================================================
# Take backups of existing dot files.
# Take backups of bin folder, but only overwrite 
# specific files in the bin dir.
# Move all git env files into the correct location.
#===================================================

INSTALL_DIR=$HOME
BACKUP_DIR=$INSTALL_DIR/dotfile_backups
DOT_FILES=(.bashrc .gitconfig .tmux.conf .vimrc .editorconfig)
BIN_DIR=$INSTALL_DIR/bin
BIN_FILES=(scripts)

NOW="$(date +'%Y-%m-%dT%H.%M.%S')"
CURRENT_BACKUP="$BACKUP_DIR/$NOW"

mkdir -p "$CURRENT_BACKUP"
mkdir -p "$CURRENT_BACKUP/bin"

# Create backup
echo "Backing up existing environment config files from $INSTALL_DIR into $CURRENT_BACKUP..."
for file in "${DOT_FILES[@]}"; do
    cp --recursive $INSTALL_DIR/$file "$CURRENT_BACKUP"
done
cp --recursive $BIN_DIR "$CURRENT_BACKUP"

# Overwrite existing env files.
echo "Copying git environment config files from $(pwd) to $INSTALL_DIR"
for file in "${DOT_FILES[@]}"; do
    cp --recursive ./$file $HOME_DIR
done
for file in "${BIN_FILES[@]}"; do
    cp --recursive ./bin/$file $BIN_DIR 
done

echo "dotfiles installed. :)"

