#!/bin/bash
################################################
# Change and list available erlang versions etc.
# Requires kerl https://github.com/kerl/kerl
################################################

if [ $# -ne 1 ]; then 
    echo "Use cherl to list installed Erlang versions, and activate them."
    echo "Usage: cherl releases|builds|installations|<VERSION>"
elif [ "$1" = "releases" ]; then
    kerl list releases 
elif [ "$1" = "builds" ]; then
    kerl list builds
elif [ "$1" = "installs" ]; then
    kerl list installs
else
    is_installation="kerl list installations | grep $1"
    # Split into [Installation, InstallationDirectory]
    vars=($is_installation)
    if [ is_installation = "" ]; then
        echo "You silly goose, ${vars[0]} isn't an installed erlang version."   
    else
        # Activate the installed erlang version.
        source "${vars[1]}/activate"
        echo "Activated Erlang version ${vars[0]}"
    fi
fi
